### ISSUE TITLE
Bypass through dispensers

### ISSUE THREAD

**Issue by StupidDrew9** [Ruinscraft/CHIP#1]
Splash/lingering potions can be created in single player, put into a dispenser, saved into a shulker box, and transferred to the server through saved toolbars. The dispenser can be placed and the potions inside can be activated with a lever without being checked.

![javaw_2018-04-08_10-35-56](https://user-images.githubusercontent.com/11621666/38468813-0db6b246-3b19-11e8-86e8-d754f7c0af6b.png)

**Comment by dextonanderson** [comment]
fixed in https://github.com/Ruinscraft/CHIP/commit/165b27c53cd90d4330430c7515647930384f5b63
