### ISSUE TITLE
Chip exception

### ISSUE THREAD

**Issue by xion87** [Ruinscraft/CHIP#5]
https://gist.github.com/xion87/aed35478845df9902d1475b353a532ae

**Comment by dextonanderson** [comment]
Hopefully this fixes your issue: https://github.com/Ruinscraft/CHIP/releases/tag/0.4.8

**Comment by dextonanderson** [comment]
Try this: https://github.com/Ruinscraft/CHIP/releases/tag/0.4.9

**Comment by xion87** [comment]
ok these exceptions seem all fixed :3
